kind: wasmer.io/App.v0
name: aether-ai
app_id: da_nkPI5tJUkwd1
owner: adamsrealm1
package: .
env:
  PYTHONEXECUTABLE: /bin/python
  PYTHONPATH: /app
  AETHER_GROQ_MODELS: openai/gpt-oss-120b,llama-3.1-8b-instant,qwen/qwen3-32b
cli_args:
- -m
- flask
- --app
- /app/server:app
- run
- --host
- 0.0.0.0
- --port
- '5000'
- --no-reload
capabilities:
  database:
    engine: mysql
annotations:
  shipitcli.com/config:
    commands:
      build: pip install -r requirements.txt
    cross_platform: wasix_wasm32
    extra_dependencies:
    - uvicorn
    framework: flask
    install_requires_all_files: false
    main_file: main.py
    port: 8080
    precompile_python: true
    python_extra_index_url: https://pythonindex.wasix.org/simple
    python_version: '3.13'
    server: uvicorn
    uses_ffmpeg: false
    uses_pandoc: false
    uv_version: 0.8.15
    wsgi_application: main:app
    database: mysql
  shipitcli.com/provider: python
  shipitcli.com/version: 0.19.8
